### ISSUE TITLE
Bug: "Error: Cannot find module 'graceful-fs'" occured when building client

### ISSUE THREAD

**Issue by yuki-takei** [weseek/crowi-plus#177]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Win 10, Ubuntu 16.04|
|crowi-plus|2.1.0-RC|
|node.js   |6.11.3|
|npm       |5.4.2|
|Using Docker|no|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

How to reproduce? (再現手順)
---------------------------

1. `NODE_ENV=production` (Perhaps it may be unnecessary)
1. `yarn install --production`
1. install plugins
    ```bash
    $ npm install --save crowi-plugin-lsx
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\uuid.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\uuid
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\uuid as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\uuid
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\semver.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\semver
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\semver as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\semver
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\nopt.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\nopt
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\nopt as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\nopt
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\mime.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\mime
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\mime as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\mime
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\json5.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\json5
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\json5 as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\json5
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\browserslist.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\browserslist
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\.bin\browserslist as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\browserslist
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\aws-sdk\node_modules\.bin\uuid.cmd as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\aws-sdk\node_modules\uuid
	npm WARN gentlyRm not removing c:\dev\Crowi\crowi-plus\node_modules\aws-sdk\node_modules\.bin\uuid as it wasn't installed by c:\dev\Crowi\crowi-plus\node_modules\aws-sdk\node_modules\uuid
	+ crowi-plugin-lsx@1.3.6
	added 3 packages, removed 1050 packages and updated 20 packages in 15.271s
    ```

1. `npm run build:prod`

What happens? (症状)
---------------------

- `npm run build:prod` failed
```
> crowi-plus@2.1.0-RC prebuild:prod c:\dev\Crowi\crowi-plus
> npm run plugin:def


> crowi-plus@2.1.0-RC plugin:def c:\dev\Crowi\crowi-plus
> node bin/generate-plugin-definitions-source.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'graceful-fs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (c:\dev\Crowi\crowi-plus\bin\generate-plugin-definitions-source.js:6:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

What is the expected result? (期待される動作)
-------------------------------------------

- build successfully

Note
----

- It was succeeded if using `yarn add crowi-plugin-lsx`
- Does `npm@5` makes something bad?
- [crowi-plus-docker-compose] users are using `npm install --save`
    - https://github.com/weseek/crowi-plus-docker-compose/blob/master/Dockerfile#L15

**Comment by yuki-takei** [comment]
It was resolved by using `npm@4`.

I decided not to adopt yarn to install plugins in docker image, because it always creates mass caches.
