### ISSUE TITLE
bug: Google OAuthを利用するとcrowi-plusのプロセスが落ちる。

### ISSUE THREAD

**Issue by MakoTano** [weseek/crowi-plus#210]
crowi-plus v2.2.3 で「Official Crowi authentication mechanism」を選択し、GoogleのOAuth認証を有効にした場合、Googleを利用したコネクト（アカウント連携）・サインアップに失敗し、crowi-plusのプロセスが落ちます。

v2.2.1にダウングレードしたところ、この現象は再現しませんでした。
バージョン指定以外のDockerfile・設定は変えていません。

Environment
------------
### Host

| item     | version |
| ---      | --- |
|OS        |centos7|
|crowi-plus|2.2.3|
|node.js   |6.11.5|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

セキュリティ設定
- Basic認証：無設定
- ゲストユーザーのアクセス： アカウントを持たないユーザーはアクセス不可
- 登録の制限： 公開
- 登録許可メールアドレスのホワイトリスト： `@sample.com` のような形で１つドメインを指定
- 認証機構設定： Official Crowi authentication mechanism
- Google 設定： Client ID、Client Secretを設定済み

### Client

| item     | version |
| ---      | --- |
|OS        |mac|
|browser   |chrome（現時点最新）|

How to reproduce? (再現手順)
---------------------------
「Googleコネクト」のケース

1. v2.2.3に対して、Google OAuthを有効にするよう前セクションにあるセキュリティ設定を施す
1. ID/Passwordを入力してログイン
1. ユーザー設定画面にて「Googleコネクト」を押す
1. crowi-plusのプロセスが落ちる

「Sign up」のケース

1. ログアウトした状態で、ログイン画面にて「Sign up」を選択
1. 「Sign up」の画面で「Sign up with Google Account」直下の赤いボタンを押す
1. crowi-plusのプロセスが落ちる

What happens? (症状)
---------------------

- Google OAuthの連携をしようとすると、crowi-plusのプロセスが落ちる

What is the expected result? (期待される動作)
-------------------------------------------

- crowi-plusのプロセスが落ちずに、正常にGoogle OAuthが利用できる。

Note
----
v2.2.1にダウングレードしたところ、この現象は再現しませんでした。
バージョン指定以外のDockerfile・設定は変えていません。

**Comment by yuki-takei** [comment]
@MakoTano ご報告ありがとうございます。再現しました。
一旦サーバーログをメモ。

```
TypeError: oauth2Client.setCredentials is not a function
    at C:\Users\Yuki\dev\crowi-plus\lib\util\googleAuth.js:52:20
    at C:\Users\Yuki\dev\crowi-plus\node_modules\google-auth-library\lib\auth\oauth2client.js:95:13
    at Request._callback (C:\Users\Yuki\dev\crowi-plus\node_modules\google-auth-library\lib\transporters.js:113:17)
    at Request.self.callback (C:\Users\Yuki\dev\crowi-plus\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (C:\Users\Yuki\dev\crowi-plus\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (C:\Users\Yuki\dev\crowi-plus\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
[ERROR] 09:55:07 TypeError
```

**Comment by yuki-takei** [comment]
googleapis 23.0.0 で発生したバグのようです。
https://github.com/google/google-auth-library-nodejs/issues/189

22.0.0 に戻したところ、手元では正常にログインできました。
直してリリースします。

**Comment by yuki-takei** [comment]
https://github.com/google/google-api-nodejs-client/issues/869

```js
oauth2Client.credentials = tokens;
```

で大丈夫みたい。

**Comment by MakoTano** [comment]
ありがとうございました！！
