### ISSUE TITLE
Bug: ページコンテンツが表示されない事がある

### ISSUE THREAD

**Issue by takuma-watanabe** [weseek/crowi-plus#243]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        ||
|crowi-plus|2.3.4|
|node.js   |6.12.3|
|npm       |4.6.1|
|Using Docker|yes|
|Using [crowi-plus-docker-compose](crowi-plus-docker-compose)|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

*(Accessing https://{CROWI_HOST}/admin helps you to fill in above versions)*

### Client

| item     | version |
| ---      | --- |
|OS        |Windows 7|
|browser   |Vivaldi 1.13.1008.40 (Stable channel) (32-bit)|

How to reproduce? (再現手順)
---------------------------

1. 2.3.4 へバージョンアップ後、ポータルトップページを表示する

What happens? (症状)
---------------------

- 以下のようにローディング画像のままとなり、コンテンツが表示されない（事がある）

![ポータルが表示されない](https://user-images.githubusercontent.com/32568002/35419401-1cf736d0-027b-11e8-9f44-9567e3c66139.png)

- Developer Tool で Console 上に JS エラーが発生している

![image](https://user-images.githubusercontent.com/32568002/35419623-5ccca8b6-027c-11e8-87ee-428b983c55bd.png)

```
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at t.value (app.92ff2b04e860c0b73f9e.bundle.js:1)
    at e.value (app.92ff2b04e860c0b73f9e.bundle.js:1)
    at app.92ff2b04e860c0b73f9e.bundle.js:1
    at Array.map (<anonymous>)
    at e.value (app.92ff2b04e860c0b73f9e.bundle.js:1)
    at app.92ff2b04e860c0b73f9e.bundle.js:1
    at <anonymous>
jquery.min.js:2 jQuery.Deferred exception: Cannot read property 'replace' of undefined TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (http://wiki.***.*******-*******m.com/js/commons.fc8cb17437f06850e02c.bundle.js:1:1915106)
    at HTMLAnchorElement.<anonymous> (http://wiki.***.*******-*******m.com/js/legacy.6be813f75af973bd8989.bundle.js:1:8454)
    at Function.each (https://cdn.jsdelivr.net/jquery/3.2.1/jquery.min.js:2:2715)
    at r.fn.init.each (https://cdn.jsdelivr.net/jquery/3.2.1/jquery.min.js:2:1003)
    at HTMLDocument.<anonymous> (http://wiki.***.*******-*******m.com/js/legacy.6be813f75af973bd8989.bundle.js:1:8356)
    at j (https://cdn.jsdelivr.net/jquery/3.2.1/jquery.min.js:2:29999)
    at k (https://cdn.jsdelivr.net/jquery/3.2.1/jquery.min.js:2:30313) undefined
r.Deferred.exceptionHook @ jquery.min.js:2
jquery.min.js:2 Uncaught TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (commons.fc8cb17437f06850e02c.bundle.js:1)
    at HTMLAnchorElement.<anonymous> (legacy.6be813f75af973bd8989.bundle.js:1)
    at Function.each (jquery.min.js:2)
    at r.fn.init.each (jquery.min.js:2)
    at HTMLDocument.<anonymous> (legacy.6be813f75af973bd8989.bundle.js:1)
    at j (jquery.min.js:2)
    at k (jquery.min.js:2)
```

What is the expected result? (期待される動作)
-------------------------------------------

- JSエラーが発生せずページが表示される

Note
----

-  `Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined` は全てのページで発生しているように見える
- ~~ただし、コンテンツが表示されない事象が発生するのはポータルトッだけ（のように感じる）~~
- ポータルトップ以外でも再現しました。
- ポータルトップにおいても再現性は100%ではなく、表示されることもある

**Comment by takuma-watanabe** [comment]
lsx プラグインを利用しているページでの再現性が高いように感じます。

**Comment by yuki-takei** [comment]
@takuma-watanabe ご報告ありがとうございました。再現確認しました。
lsx なしでも起こりますね。なる早で修正してリリースします。

**Comment by yuki-takei** [comment]
@takuma-watanabe v2.3.5 リリースしました。
crowi-plugin-lsx と両方アップグレードしてテストしてみていただけますでしょうか。

よろしくお願いします。

**Comment by takuma-watanabe** [comment]
@yuki-takei 早急な対応ありがとうございました。
アップグレードして確認し、問題ありませんでした。
