### ISSUE TITLE
Bug: LDAP authentication failure

### ISSUE THREAD

**Issue by Mizuho32** [weseek/crowi-plus#314]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        | ArchLinux |
|crowi-plus|2.4.5-RC|
|node.js   |6.12.0|
|npm       |3.10.10|
|yarn       |1.5.1|
|Using Docker|yes (both)|
|Using [crowi-plus-docker-compose][crowi-plus-docker-compose]|yes|

[crowi-plus-docker-compose]: https://github.com/weseek/crowi-plus-docker-compose

### LDAP(AD)

| item     | version |
| ---      | --- |
|OS        | ubuntu server 16.04 |
|samba4 | Version 4.9.0pre1-GIT-e9d42e5 |

### Client

| item     | version |
| ---      | --- |
|OS        |Linux|
|browser   |Firefox/Chrome|

How to reproduce? (再現手順)
---------------------------

1. Launch LDAP, crowi-plus
1. Access and login

What happens? (症状)
---------------------

- Internal Server Error

```
ValidationError: User validation failed: username: Path `username` is required.
    at MongooseError.ValidationError (/opt/crowi-plus/node_modules/mongoose/lib/error/validation.js:27:11)
    at model.Document.invalidate (/opt/crowi-plus/node_modules/mongoose/lib/document.js:1654:32)                  
    at /opt/crowi-plus/node_modules/mongoose/lib/document.js:1526:17
    at Immediate.<anonymous> (/opt/crowi-plus/node_modules/mongoose/lib/schematype.js:785:9)                      
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)                                                                           
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

What is the expected result? (期待される動作)
-------------------------------------------

- Login

**Comment by yuki-takei** [comment]
@Mizuho32 Thank you for your report.
I'll try to reproduce.

**Comment by yuki-takei** [comment]
@Mizuho32 
Does the user in LDAP have the `uid` attribute ?

If not, please set `username` of `Attribute Mapping` in `/admin/security` page.
![image](https://user-images.githubusercontent.com/1638767/37824753-028908c8-2ed1-11e8-9c5f-973e172433a4.png)

Anyway, causing 500 is a system bug.
I'll fix it whether you succeed configuring the above or not.

**Comment by Mizuho32** [comment]
Thanks for your great & quick solution.
It works fine!

やっぱり設定画面はよく見ないとだめですね・・・
ともあれ、ありがとうございます!😄

**Comment by yuki-takei** [comment]
TODO
-------

- [ ] Throw an exception when `usernameToBeRegistered` is null
    - https://github.com/weseek/crowi-plus/blob/3dd0a7f7061571a6b3e8f8676a7bb1a3bb45ff12/lib/routes/login-passport.js#L111
- [ ] Catch the exception and show error when login
    - https://github.com/weseek/crowi-plus/blob/3dd0a7f7061571a6b3e8f8676a7bb1a3bb45ff12/lib/routes/login-passport.js#L128
- [ ] Set flash message when test ldap credentials
    - https://github.com/weseek/crowi-plus/blob/3dd0a7f7061571a6b3e8f8676a7bb1a3bb45ff12/lib/routes/login-passport.js#L175

**Comment by kaoritokashiki** [comment]
1. I could not reproduce the bug `Creating user data failed after LDAP authentication succeed`

1. I just improved User authentication error handling  that Yuki San mentioned
https://github.com/weseek/growi/issues/314#issuecomment-375633848

I close this issue. Thank you.
