### ISSUE TITLE
初回アクセス時に「TypeError: Cannot read property 'buildIndex' of null」が出力されます

### ISSUE THREAD

**Issue by trisland** [weseek/crowi-plus#92]
Environment
------------

- [OS] CentOS 7.3
- [crowi-plus] 1.2.0-RC
- [node.js] 6.10.3
- [browser] ?.?.?

How to reproduce? (再現手順)
---------------------------

1. データベース用意
   ```bash
   systemctl start mongod
   mongo
   ```

   ```mongo
   use crowidb
   db.createUser({user: "crowi", pwd: "DB-PASSWD", roles: [{role: "readWrite", db: "crowidb"}]})
   ```

1. インストール
   ```bash
   cd /var/lib
   git clone --depth=1 https://github.com/weseek/crowi-plus
   
   cd crowi-plus
   npm install -g {npm,yarn} && npm upgrade -g {npm,yarn}
   yarn
   ```

1. 起動
   ```bash
   MONGO_URI="mongodb://crowi:DB-PASSWD@localhost/crowidb" npm start
   ```

What's happen? (症状)
---------------------

以下のエラーが出力されます。

```
TypeError: Cannot read property 'buildIndex' of null
    at /var/lib/crowi-plus/lib/util/middlewares.js:266:13
    at Layer.handle [as handle_request] (/var/lib/crowi-plus/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/crowi-plus/node_modules/express/lib/router/route.js:137:13)
    at /var/lib/crowi-plus/lib/util/middlewares.js:258:12
    at Layer.handle [as handle_request] (/var/lib/crowi-plus/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/lib/crowi-plus/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/lib/crowi-plus/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/lib/crowi-plus/node_modules/express/lib/router/layer.js:95:5)
    at /var/lib/crowi-plus/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:275:10)
    at logger (/var/lib/crowi-plus/node_modules/morgan/index.js:144:5)
    at Layer.handle [as handle_request] (/var/lib/crowi-plus/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/crowi-plus/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle [as handle_request] (/var/lib/crowi-plus/node_modules/express/lib/router/layer.js:91:12)
    at trim_prefix (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/crowi-plus/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:335:12)
    at next (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:275:10)
    at /var/lib/crowi-plus/node_modules/i18next-express-middleware/lib/index.js:80:7
    at I18n.loadLanguages (/var/lib/crowi-plus/node_modules/i18next/dist/commonjs/i18next.js:357:33)
    at /var/lib/crowi-plus/node_modules/i18next-express-middleware/lib/index.js:79:13
    at Layer.handle [as handle_request] (/var/lib/crowi-plus/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/lib/crowi-plus/node_modules/express/lib/router/index.js:317:13)
    at /var/lib/crowi-plus/node_modules/express/lib/router/index.js:284:7
GET /installer 500 5.767 ms - 3027
```

どうかよろしくお願いいたします。

**Comment by yuki-takei** [comment]
報告ありがとうございます。症状は心当たりがあるので近日中にちょっと見てみますね。

# ElasticSearch を使わない場合に失敗してるんだろうなと予測…

**Comment by yuki-takei** [comment]
@trisland master ブランチに修正されるであろう変更をコミットしました。再現するかどうか確かめていただけると助かります。

**Comment by trisland** [comment]
@yuki-takei 早速、ご対応いただきありがとうございます。
無事、アクセスできることを確認いたしました。PukiWikiの代わりに使用させていただきます。

今後ともどうぞよろしくお願いいたします。
